spring:
  application:
    name: gateway-server

  config:
    import: optional:configserver:http://config-server:8888
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"

  cloud:
    gateway:
      routes:

        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**

        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/skills/**

        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/api/departments/**

        - id: approval-service
          uri: lb://approval-service
          predicates:
            - Path=/api/approvals/**

        - id: masterdata-service
          uri: lb://masterdata-service
          predicates:
            - Path=/api/master-data/**
