

spring:
  cloud:
    gateway:
      routes:

        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**

        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/skills/**

        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/api/departments/**

        - id: approval-service
          uri: lb://approval-service
          predicates:
            - Path=/api/approvals/**

        - id: masterdata-service
          uri: lb://masterdata-service
          predicates:
            - Path=/api/master-data/**





